"""Bundled pan.dev endpoint catalog — loader and lookup helpers.

endpoint_catalog.json is generated by scripts/gen_endpoint_catalog.py from the
MIT-licensed pan.dev OpenAPI specs (trees: sase, scm, access). It maps every
documented endpoint to its "Current" server base URL, and records the git blob
SHA of every spec file so scm_check_updates can detect upstream spec drift.
"""

from __future__ import annotations

import functools
import json
from importlib import resources
from typing import Any

# Families searched first when resolving an SDK resource name to a collection
# endpoint — the SCM config API is what the SDK wraps, so it wins ties.
_FAMILY_PRIORITY = (
    "scm/config",
    "access/prisma-access-config",
    "access/ztna",
    "access/adem",
    "access/insights",
    "access/browser-mgmt",
)


@functools.lru_cache(maxsize=1)
def load_catalog() -> dict[str, Any]:
    """Parse the bundled catalog JSON once per process."""
    raw = resources.files(__package__).joinpath("endpoint_catalog.json").read_text()
    return json.loads(raw)


@functools.lru_cache(maxsize=1)
def _collection_index() -> dict[str, str]:
    """slug ("ike-gateways") → absolute collection URL, first family wins."""
    catalog = load_catalog()
    specs: dict[str, Any] = catalog.get("specs", {})
    ordered = [f for f in _FAMILY_PRIORITY if f in specs] + sorted(
        f for f in specs if f not in _FAMILY_PRIORITY
    )
    index: dict[str, str] = {}
    for family in ordered:
        for meta in specs[family]["files"].values():
            base = meta.get("base", "")
            for path in meta.get("paths", {}):
                if "{" in path:
                    continue  # detail/action endpoints — only collections resolve by name
                slug = path.rstrip("/").rsplit("/", 1)[-1]
                if slug and slug not in index:
                    index[slug] = f"{base}{path}"
    return index


def find_endpoint(resource: str) -> str | None:
    """Resolve an SDK resource attribute (e.g. "internal_dns_server") to the
    documented collection URL, trying singular and plural slug forms."""
    slug = resource.strip().lower().replace("_", "-")
    candidates = [slug, f"{slug}s", f"{slug}es"]
    if slug.endswith("y"):
        candidates.append(f"{slug[:-1]}ies")
    index = _collection_index()
    for c in candidates:
        url = index.get(c)
        if url:
            return url
    return None


def catalog_meta() -> dict[str, Any]:
    """Summary for scm_check_updates: generation info + per-file blob SHAs."""
    catalog = load_catalog()
    files: dict[str, str] = dict(catalog.get("file_shas", {}))
    if not files:  # catalogs generated before file_shas existed
        for family_meta in catalog.get("specs", {}).values():
            for rel, meta in family_meta["files"].items():
                files[rel] = meta.get("sha", "")
    return {
        "generated_at": catalog.get("generated_at", ""),
        "pan_dev_commit": catalog.get("pan_dev_commit", ""),
        "trees": catalog.get("trees", []),
        "total_paths": catalog.get("total_paths", 0),
        "families": {f: len(m["files"]) for f, m in catalog.get("specs", {}).items()},
        "files": files,
    }
