"""Pre-request validation against OpenAPI schemas.

Reduces opaque HTTP 400s by validating query parameters and request bodies
against the endpoint's OpenAPI schema **before** making the API call.

The schema index (``resources/endpoint_schemas.json``) is generated by
``scripts/gen_endpoint_catalog.py --include-schemas``.  When the file is
absent (regenerated catalog without schemas), validation is a no-op —
the functions return empty error lists so callers don't need to guard.

Usage:
    from scm_mcp_mssp.utils.validation import validate_body
    errors = validate_body("POST /insights/v2/query/connected_users", body)
    if errors:
        ...  # surface to caller, optionally abort
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Schema index — lazy-loaded, cached at module level
# ---------------------------------------------------------------------------

_schema_index: dict[str, dict[str, Any]] | None = None
"""Loaded schema index or None if not yet loaded / file absent."""

_SCHEMA_PATH = Path(__file__).resolve().parent.parent / "resources" / "endpoint_schemas.json"


def _load_schema_index() -> dict[str, dict[str, Any]]:
    """Load the endpoint schema index, returning {} if unavailable."""
    global _schema_index
    if _schema_index is not None:
        return _schema_index

    if not _SCHEMA_PATH.exists():
        _schema_index = {}
        return _schema_index

    try:
        with open(_SCHEMA_PATH) as fh:
            data = json.load(fh)
        _schema_index = data.get("endpoints", data) if isinstance(data, dict) else {}
    except Exception:
        _schema_index = {}

    return _schema_index


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def validate_params(endpoint_key: str, params: dict[str, Any]) -> list[str]:
    """Validate query/header/path parameters against the endpoint's schema.

    Args:
        endpoint_key: ``"METHOD /path"`` (e.g. ``"GET /v1/remote-networks"``).
        params:       Query parameter dict to validate.

    Returns:
        List of human-readable error messages.  Empty list = valid or no schema.
    """
    index = _load_schema_index()
    schema = index.get(endpoint_key)
    if schema is None:
        return []

    param_schemas = schema.get("parameters")
    if not param_schemas:
        return []

    errors: list[str] = []
    for pspec in param_schemas:
        name = pspec.get("name", "")
        required = pspec.get("required", False)
        ptype = pspec.get("schema", {}).get("type", "string")

        if name not in params or params[name] is None or params[name] == "":
            if required:
                errors.append(f"Missing required parameter: {name}")
            continue

        value = params[name]
        # Simple type checking
        if ptype == "integer" and not isinstance(value, int):
            try:
                int(value)
            except (ValueError, TypeError):
                errors.append(f"Parameter {name!r}: expected integer, got {type(value).__name__}")
        elif ptype == "boolean" and not isinstance(value, bool):
            errors.append(f"Parameter {name!r}: expected boolean, got {type(value).__name__}")

        # Enum check
        enum_values = pspec.get("schema", {}).get("enum")
        if enum_values and value not in enum_values:
            errors.append(f"Parameter {name!r}: {value!r} not in allowed values: {enum_values}")

    return errors


def validate_body(endpoint_key: str, body: dict[str, Any]) -> list[str]:
    """Validate a request body against the endpoint's JSON Schema.

    Args:
        endpoint_key: ``"METHOD /path"`` (e.g. ``"POST /insights/v2/query/connected_users"``).
        body:         The request body dict to validate.

    Returns:
        List of human-readable error messages.  Empty list = valid or no schema.
    """
    index = _load_schema_index()
    schema = index.get(endpoint_key)
    if schema is None:
        return []

    body_schema = schema.get("requestBody")
    if not body_schema:
        return []

    try:
        import jsonschema

        jsonschema.validate(instance=body, schema=body_schema)
    except jsonschema.ValidationError as exc:
        # Format the error path + message for readability
        path = " → ".join(str(p) for p in exc.absolute_path) if exc.absolute_path else "(root)"
        return [f"{path}: {exc.message}"]
    except jsonschema.SchemaError as exc:
        return [f"Schema error for {endpoint_key}: {exc.message}"]
    except Exception as exc:
        return [f"Validation error: {exc}"]

    return []


def has_schema(endpoint_key: str) -> bool:
    """Check whether a schema exists for the given endpoint key."""
    index = _load_schema_index()
    return endpoint_key in index


def schema_coverage() -> dict[str, Any]:
    """Return coverage stats for the loaded schema index.

    Returns:
        Dict with ``total_endpoints`` and ``covered_endpoints`` counts.
    """
    index = _load_schema_index()
    return {
        "total_endpoints": len(index),
        "schema_file": str(_SCHEMA_PATH),
        "schema_file_exists": _SCHEMA_PATH.exists(),
    }
