#!/usr/bin/env python
"""Generate read-only MCP tool scaffolds from a pan.dev OpenAPI spec family.

Reads the spec file list for a family from the bundled endpoint catalog
(resources/endpoint_catalog.json), loads each spec — from a local pan.dev
checkout (--specs-dir) or raw.githubusercontent.com pinned to the catalog's
commit — and emits a Python module containing:

  * one `_fetch_<slug>()` helper per collection GET endpoint (no `{id}`
    paths), with typed query params taken from the spec
  * a `register_<prefix>_tools(mcp, get_client)` function exposing one
    @mcp.tool() stub per endpoint

The output is a *scaffold*: review it, consolidate related endpoints into
fewer ergonomic tools (an MCP server's tool count is client-visible context),
and move it into src/scm_mcp_mssp/tools/.

Usage:
    uv run --with pyyaml python scripts/gen_tool_from_spec.py sase/mt-interconnect \
        [--prefix spi] [--out scaffold_spi.py] [--specs-dir DIR]
"""

from __future__ import annotations

import argparse
import json
import keyword
import re
import sys
import urllib.request
from pathlib import Path

import yaml

RAW_BASE = "https://raw.githubusercontent.com/PaloAltoNetworks/pan.dev"

_TYPE_MAP = {"string": "str", "integer": "int", "boolean": "bool", "number": "float"}


def _snake(name: str) -> str:
    s = re.sub(r"[^0-9a-zA-Z]+", "_", name)
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", s).lower().strip("_")
    return f"{s}_" if keyword.iskeyword(s) else s


def _load_spec(rel: str, specs_dir: str | None, commit: str) -> dict:
    if specs_dir:
        text = (Path(specs_dir) / rel).read_text()
    else:
        url = f"{RAW_BASE}/{commit}/{rel}"
        with urllib.request.urlopen(url, timeout=30) as resp:  # noqa: S310
            text = resp.read().decode()
    return json.loads(text) if rel.endswith(".json") else yaml.safe_load(text)


def _common_prefix(paths: list[str]) -> str:
    """Longest common leading /segment/ prefix across the family's paths."""
    if not paths:
        return ""
    split = [p.strip("/").split("/") for p in paths]
    common: list[str] = []
    for segs in zip(*split, strict=False):
        if len(set(segs)) == 1:
            common.append(segs[0])
        else:
            break
    return "/" + "/".join(common) if common else ""


def _endpoint_entries(family: str, specs_dir: str | None) -> tuple[str, list[dict]]:
    from scm_mcp_mssp.resources.endpoint_catalog import load_catalog

    catalog = load_catalog()
    fam = catalog["specs"].get(family)
    if fam is None:
        sys.exit(f"family {family!r} not in catalog; have: {', '.join(sorted(catalog['specs']))}")
    commit = catalog["pan_dev_commit"]

    entries: list[dict] = []
    for rel, meta in sorted(fam["files"].items()):
        gets = [p for p, methods in meta["paths"].items() if "get" in methods and "{" not in p]
        if not gets:
            continue
        doc = _load_spec(rel, specs_dir, commit)
        base = meta.get("base", "")
        for path in sorted(gets):
            op = doc.get("paths", {}).get(path, {}).get("get", {})
            params = [
                {
                    "name": prm["name"],
                    "py": _snake(prm["name"]),
                    "type": _TYPE_MAP.get((prm.get("schema") or {}).get("type"), "str"),
                }
                for prm in op.get("parameters", [])
                if prm.get("in") == "query" and prm.get("name")
            ]
            entries.append(
                {
                    "path": path,
                    "url": f"{base}{path}",
                    "summary": (op.get("summary") or "").strip(),
                    "description": " ".join((op.get("description") or "").split())[:300],
                    "params": params,
                    "spec_file": rel,
                }
            )
    return commit, entries


def _emit(family: str, prefix: str, commit: str, entries: list[dict]) -> str:
    strip = _common_prefix([e["path"] for e in entries])
    lines: list[str] = [
        '"""',
        f"Read-only tools for the pan.dev `{family}` API family.",
        "",
        "Scaffold generated by scripts/gen_tool_from_spec.py from pan.dev",
        f"@ {commit[:12]} — review, consolidate, and curate before registering.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import json",
        "from typing import Any",
        "",
        "from mcp.server.fastmcp import FastMCP",
        "",
        "from ..audit.extractor import _bearer_session_for",
        "from ..utils.logging import get_logger",
        "",
        "logger = get_logger(__name__)",
        "",
        "_MAX_CHARS = 15000",
        "",
        "",
        "def _get_json(client: Any, url: str, params: dict[str, Any]) -> tuple[int, Any]:",
        '    """GET url with a fresh bearer session; return (status, parsed-or-text)."""',
        "    session = _bearer_session_for(client)",
        "    resp = session.get(",
        "        url, params={k: v for k, v in params.items() if v is not None}, timeout=(5, 30)",
        "    )",
        "    try:",
        "        return resp.status_code, resp.json()",
        "    except Exception:",
        "        return resp.status_code, (resp.text or '')[:500]",
        "",
        "",
        "def _render(title: str, url: str, status: int, data: Any) -> str:",
        "    if status in (401, 403):",
        "        return (",
        '        f"# {title}\\n\\n⚠️ HTTP {status} — the service account lacks access to "',
        '        f"`{url}`. This API may require a multitenant (MSP) role or the feature "',
        '        f"may not be provisioned for this tenant."',
        "        )",
        "    if status == 404:",
        '        return f"# {title}\\n\\nHTTP 404 — not provisioned for this tenant."',
        "    if status >= 500:",
        '        return f"# {title}\\n\\nHTTP {status} — upstream backend error from `{url}` (body suppressed)."',
        "    if status != 200:",
        '        return f"# {title}\\n\\nHTTP {status} from `{url}`:\\n\\n{data}"',
        "    items = data.get('data', data.get('items', data)) if isinstance(data, dict) else data",
        "    count = len(items) if isinstance(items, list) else 1",
        "    body = json.dumps(items, indent=2, default=str)",
        "    if len(body) > _MAX_CHARS:",
        "        body = body[:_MAX_CHARS] + '\\n… (truncated)'",
        '    return f"# {title} ({count})\\n\\n```json\\n{body}\\n```"',
        "",
    ]

    fetch_names: list[str] = []
    for e in entries:
        slug = _snake(e["path"][len(strip) :].strip("/") or "root")
        fn = f"_fetch_{slug}"
        fetch_names.append((fn, slug, e))  # type: ignore[arg-type]
        sig_params = "".join(f", {p['py']}: {p['type']} | None = None" for p in e["params"])
        send = ", ".join(f'"{p["name"]}": {p["py"]}' for p in e["params"])
        lines += [
            "",
            f"def {fn}(client: Any{sig_params}) -> tuple[int, Any]:",
            f'    """{e["summary"] or slug} — GET {e["path"]}"""',
            f'    return _get_json(client, "{e["url"]}", {{{send}}})',
            "",
        ]

    lines += [
        "",
        f"def register_{prefix}_tools(mcp: FastMCP, get_client: Any) -> None:",
        f'    """Register {family} read-only tools."""',
    ]
    for fn, slug, e in fetch_names:  # type: ignore[misc]
        tool = f"scm_{prefix}_{slug}"
        sig_params = "".join(f", {p['py']}: {p['type']} | None = None" for p in e["params"])
        fwd = "".join(f", {p['py']}={p['py']}" for p in e["params"])
        doc_desc = e["description"] or e["summary"] or slug
        lines += [
            "",
            "    @mcp.tool()",
            f'    def {tool}(tenant_id: str = ""{sig_params}) -> str:',
            f'        """{e["summary"] or slug}.',
            "",
            f"        {doc_desc}",
            "",
            f"        GET `{e['path']}` (pan.dev {family}, spec: {e['spec_file'].rsplit('/', 1)[-1]})",
            '        """',
            "        client = get_client(tenant_id)",
            f"        status, data = {fn}(client{fwd})",
            f'        return _render("{e["summary"] or slug}", "{e["url"]}", status, data)',
        ]
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("family", help='catalog family, e.g. "sase/mt-interconnect"')
    ap.add_argument("--prefix", help="tool name prefix (default: derived from family)")
    ap.add_argument("--out", help="output file (default: scaffold_<prefix>.py)")
    ap.add_argument("--specs-dir", help="existing pan.dev checkout (skips raw fetch)")
    args = ap.parse_args()

    prefix = args.prefix or _snake(args.family.split("/", 1)[1])
    commit, entries = _endpoint_entries(args.family, args.specs_dir)
    if not entries:
        sys.exit(f"no collection GET endpoints found for {args.family}")
    code = _emit(args.family, prefix, commit, entries)
    out = Path(args.out or f"scaffold_{prefix}.py")
    out.write_text(code)
    print(f"wrote {out} — {len(entries)} endpoints from {args.family} @ {commit[:12]}")


if __name__ == "__main__":
    main()
