"""
SCM config cloner — sanitise a backup snapshot and replay it into a target
folder / tenant.

Workflow:
  1. Load a backup JSON produced by scm_config_backup.
  2. Sanitise each object: strip system fields, rewrite the folder, scrub PSKs,
     optionally apply a name prefix and anonymise IP addresses.
  3. Push objects to the target tenant in dependency order (tags → addresses →
     groups → profiles → rules → deployment).
  4. Return a detailed push report (or a dry-run preview).

PSK handling: pre-shared keys in IKE gateways are ALWAYS replaced with
  CHANGEME_<gateway-name>  — they must be set manually before committing.

Dependency push order
─────────────────────
Tier 0  tags, services, EDLs, server profiles, crypto profiles, sec profiles
Tier 1  addresses, service groups, log-forwarding profiles, zone-protection
Tier 2  address groups, app groups, HIP objects
Tier 3  HIP profiles, security zones
Rules   security (pre), security (post), NAT, decryption, app-override
Deploy  IKE gateways, IPSec tunnels, remote networks, service connections
"""

from __future__ import annotations

import copy
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from ..utils.logging import get_logger

logger = get_logger(__name__)

# Fields generated by SCM — must not be sent on create
_SYSTEM_FIELDS = frozenset(
    {
        "id",
        "uid",
        "@uid",
        "@loc",
        "audit_comment",
        "modified_at",
        "created_at",
        "modified_by",
        "created_by",
        "last_modified_by",
        "etag",
        "_position",
    }
)

# Fixed folder names required by the SCM API for deployment resources
_FOLDER_REMOTE_NETWORKS = "Remote Networks"
_FOLDER_SERVICE_CONNECTIONS = "Service Connections"
_FOLDER_MOBILE_USERS = "Mobile Users"

# Push order: (snapshot_attr, sdk_attr, folder_mode)
# folder_mode: "customer" → target_folder, else the literal SCM folder name
_PUSH_ORDER: list[tuple[str, str, str]] = [
    # ── Tier 0: no inter-object dependencies ──────────────────────────────
    ("tags", "tag", "customer"),
    ("services", "service", "customer"),
    ("edls", "external_dynamic_list", "customer"),
    ("http_server_profiles", "http_server_profile", "customer"),
    ("syslog_profiles", "syslog_server_profile", "customer"),
    ("ike_crypto_profiles", "ike_crypto_profile", _FOLDER_REMOTE_NETWORKS),
    ("ipsec_crypto_profiles", "ipsec_crypto_profile", _FOLDER_REMOTE_NETWORKS),
    ("anti_spyware_profiles", "anti_spyware_profile", "customer"),
    ("vulnerability_profiles", "vulnerability_protection_profile", "customer"),
    ("dns_security_profiles", "dns_security_profile", "customer"),
    ("decryption_profiles", "decryption_profile", "customer"),
    ("file_blocking_profiles", "file_blocking_profile", "customer"),
    ("wildfire_profiles", "wildfire_antivirus_profile", "customer"),
    ("url_access_profiles", "url_access_profile", "customer"),
    # ── Tier 1 ────────────────────────────────────────────────────────────
    ("addresses", "address", "customer"),
    ("service_groups", "service_group", "customer"),
    ("log_forwarding_profiles", "log_forwarding_profile", "customer"),
    ("zone_protection_profiles", "zone_protection_profile", "customer"),
    ("hip_objects", "hip_object", "customer"),
    # ── Tier 2 ────────────────────────────────────────────────────────────
    ("address_groups", "address_group", "customer"),
    ("application_groups", "application_group", "customer"),
    # ── Tier 3 ────────────────────────────────────────────────────────────
    ("hip_profiles", "hip_profile", "customer"),
    ("zones", "security_zone", "customer"),
]

_RULE_ORDER: list[tuple[str, str, str | None]] = [
    ("security_rules_pre", "security_rule", "pre"),
    ("security_rules_post", "security_rule", "post"),
    ("nat_rules", "nat_rule", None),
    ("decryption_rules", "decryption_rule", None),
    ("app_override_rules", "app_override_rule", None),
]

_DEPLOY_ORDER: list[tuple[str, str, str]] = [
    ("ike_gateways", "ike_gateway", _FOLDER_REMOTE_NETWORKS),
    ("ipsec_tunnels", "ipsec_tunnel", _FOLDER_REMOTE_NETWORKS),
    ("remote_networks", "remote_network", _FOLDER_REMOTE_NETWORKS),
    ("service_connections", "service_connection", _FOLDER_SERVICE_CONNECTIONS),
    ("bandwidth_allocations", "bandwidth_allocation", _FOLDER_REMOTE_NETWORKS),
]

_IP_RE = re.compile(
    r"\b((?:(?:25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(?:25[0-5]|2[0-4]\d|[01]?\d\d?))"
    r"((?:/\d{1,2})?)\b"
)


@dataclass
class PushResult:
    resource_type: str
    name: str
    status: str  # "created" | "skipped" | "overwritten" | "dry_run" | "failed"
    detail: str = ""


@dataclass
class CloneReport:
    source_file: str
    target_folder: str
    target_tenant_id: str
    dry_run: bool
    results: list[PushResult] = field(default_factory=list)
    psk_warnings: list[str] = field(default_factory=list)

    # ── Counts ──────────────────────────────────────────────────────────
    @property
    def created(self) -> int:
        return sum(1 for r in self.results if r.status in ("created", "dry_run"))

    @property
    def skipped(self) -> int:
        return sum(1 for r in self.results if r.status == "skipped")

    @property
    def overwritten(self) -> int:
        return sum(1 for r in self.results if r.status == "overwritten")

    @property
    def failed(self) -> int:
        return sum(1 for r in self.results if r.status == "failed")

    def to_markdown(self) -> str:
        lines: list[str] = []
        mode = "DRY RUN PREVIEW" if self.dry_run else "PUSH COMPLETE"
        lines.append(f"# SCM Config Clone — {mode}")
        lines.append(f"\n**Source:** `{self.source_file}`  ")
        lines.append(f"**Target folder:** `{self.target_folder}`  ")
        if self.target_tenant_id:
            lines.append(f"**Target tenant:** `{self.target_tenant_id}`  ")
        lines.append("")

        action = "Would create" if self.dry_run else "Created"
        lines.append("## Summary\n")
        lines.append("| Outcome | Count |")
        lines.append("|---|---|")
        lines.append(f"| {action} | {self.created} |")
        lines.append(f"| Skipped (conflict) | {self.skipped} |")
        if not self.dry_run:
            lines.append(f"| Overwritten | {self.overwritten} |")
        lines.append(f"| Failed | {self.failed} |")
        lines.append(f"| **Total** | **{len(self.results)}** |")

        if self.psk_warnings:
            lines.append("\n## ⚠️ PSK Placeholders — Set Before Committing\n")
            lines.append("The following IKE gateways had their pre-shared keys replaced:")
            for w in self.psk_warnings:
                lines.append(f"- `{w}`")
            lines.append(
                "\nSet the real PSK via SCM UI or `scm_ike_gateway_update` before pushing commit."
            )

        # Group results by type
        by_type: dict[str, list[PushResult]] = {}
        for r in self.results:
            by_type.setdefault(r.resource_type, []).append(r)

        if self.results:
            lines.append("\n## Detail\n")
            for rtype, items in by_type.items():
                lines.append(f"### {rtype} ({len(items)})\n")
                lines.append("| Name | Status | Detail |")
                lines.append("|---|---|---|")
                for r in items:
                    lines.append(f"| `{r.name}` | {r.status} | {r.detail} |")
                lines.append("")

        if self.failed > 0:
            lines.append("\n## ❌ Failures\n")
            for r in self.results:
                if r.status == "failed":
                    lines.append(f"- **{r.resource_type}** `{r.name}`: {r.detail}")

        return "\n".join(lines)


def _strip_system_fields(obj: dict[str, Any]) -> dict[str, Any]:
    return {k: v for k, v in obj.items() if k not in _SYSTEM_FIELDS}


def _anonymise_ips(obj: dict[str, Any], ip_map: dict[str, str]) -> dict[str, Any]:
    """Replace IPv4 addresses in a dict (recursively) with template vars."""
    text = json.dumps(obj)

    def _replace(m: re.Match[str]) -> str:
        ip = m.group(1)
        suffix = m.group(2)
        if ip not in ip_map:
            n = len(ip_map) + 1
            ip_map[ip] = f"{{{{IP_{n}}}}}"
        return str(ip_map[ip]) + str(suffix)

    return dict(json.loads(_IP_RE.sub(_replace, text)))


def _scrub_psk(obj: dict[str, Any], gateway_name: str) -> tuple[dict[str, Any], bool]:
    """Replace PSK in an IKE gateway dict. Returns (modified_obj, was_scrubbed)."""
    obj = copy.deepcopy(obj)
    scrubbed = False
    try:
        auth = obj.get("authentication", {})
        if "pre_shared_key" in auth:
            auth["pre_shared_key"]["key"] = f"CHANGEME_{gateway_name}"
            scrubbed = True
        elif isinstance(auth.get("pre_shared_key"), str):
            auth["pre_shared_key"] = f"CHANGEME_{gateway_name}"
            scrubbed = True
    except Exception:
        pass
    return obj, scrubbed


def _apply_name_prefix(obj: dict[str, Any], prefix: str) -> dict[str, Any]:
    if prefix and "name" in obj:
        obj = dict(obj)
        obj["name"] = f"{prefix}{obj['name']}"
    return obj


def _sanitise(
    obj: dict[str, Any],
    *,
    target_folder: str,
    name_prefix: str,
    anonymise_ips: bool,
    ip_map: dict[str, str],
    is_ike_gateway: bool = False,
) -> tuple[dict[str, Any], str | None]:
    """
    Returns (sanitised_obj, psk_warning_or_None).
    """
    o = _strip_system_fields(copy.deepcopy(obj))
    o["folder"] = target_folder

    psk_warning: str | None = None
    if is_ike_gateway:
        name = obj.get("name", "unknown")
        o, scrubbed = _scrub_psk(o, name)
        if scrubbed:
            psk_warning = f"{name_prefix}{name}" if name_prefix else name

    if name_prefix:
        o = _apply_name_prefix(o, name_prefix)

    if anonymise_ips:
        o = _anonymise_ips(o, ip_map)

    return o, psk_warning


def _push_one(
    client: Any,
    sdk_attr: str,
    payload: dict[str, Any],
    on_conflict: str,
    dry_run: bool,
    resource_type: str,
) -> PushResult:
    name = payload.get("name", "<unknown>")
    if dry_run:
        return PushResult(
            resource_type, name, "dry_run", f"would create in folder '{payload.get('folder', '')}'"
        )
    try:
        resource = getattr(client, sdk_attr)
        resource.create(payload)
        logger.info("clone_object_created", type=resource_type, name=name)
        return PushResult(resource_type, name, "created")
    except Exception as exc:
        err = str(exc)
        is_conflict = any(
            x in type(exc).__name__ for x in ("Conflict", "NameNotUnique", "ObjectNotUnique")
        )
        if not is_conflict:
            is_conflict = any(
                p in err.lower() for p in ("already exists", "name not unique", "conflict")
            )
        if is_conflict and on_conflict == "skip":
            return PushResult(resource_type, name, "skipped", "already exists")
        if is_conflict and on_conflict == "overwrite":
            try:
                resource = getattr(client, sdk_attr)
                existing = resource.fetch(name=name, folder=payload.get("folder", ""))
                payload_with_id = dict(payload)
                if hasattr(existing, "id"):
                    payload_with_id["id"] = str(existing.id)
                resource.update(payload_with_id)
                return PushResult(resource_type, name, "overwritten")
            except Exception as upd_exc:
                return PushResult(resource_type, name, "failed", str(upd_exc)[:120])
        logger.warning("clone_object_failed", type=resource_type, name=name, error=err)
        return PushResult(resource_type, name, "failed", err[:120])


def clone_config(
    client: Any,
    source_backup_file: str,
    target_folder: str,
    *,
    name_prefix: str = "",
    anonymise_ips: bool = False,
    include_deployment: bool = False,
    skip_rules: bool = False,
    on_conflict: str = "skip",
    dry_run: bool = True,
    resource_filter: set[str] | None = None,
) -> CloneReport:
    """
    Load *source_backup_file*, sanitise every object, and push to
    *target_folder* on *client*.

    Parameters
    ----------
    client          : Authenticated Scm client.
    source_backup_file : Path to JSON produced by scm_config_backup.
    target_folder   : Destination SCM folder name.
    name_prefix     : Optional prefix applied to every object name.
    anonymise_ips   : Replace IPv4 literals with {{IP_N}} template vars.
    include_deployment : Also clone IKE gateways, IPSec tunnels, RNs, SCs.
    skip_rules      : Omit all policy rules.
    on_conflict     : 'skip' (default) or 'overwrite'.
    dry_run         : If True, no API writes are made (default: True).
    resource_filter : If set, only process resource types in this set.
    """
    data = json.loads(Path(source_backup_file).read_text())
    resources: dict[str, list[dict[str, Any]]] = data.get("resources", {})

    report = CloneReport(
        source_file=source_backup_file,
        target_folder=target_folder,
        target_tenant_id="",
        dry_run=dry_run,
    )
    ip_map: dict[str, str] = {}

    def _process_batch(
        snap_key: str,
        sdk_attr: str,
        folder: str,
        *,
        is_ike_gateway: bool = False,
        position: str | None = None,
    ) -> None:
        if resource_filter and snap_key not in resource_filter:
            return
        objects = resources.get(snap_key, [])
        if not objects:
            return
        for obj in objects:
            obj_folder = folder if folder != "customer" else target_folder
            o, psk_w = _sanitise(
                obj,
                target_folder=obj_folder,
                name_prefix=name_prefix,
                anonymise_ips=anonymise_ips,
                ip_map=ip_map,
                is_ike_gateway=is_ike_gateway,
            )
            if psk_w:
                report.psk_warnings.append(psk_w)
            if position:
                o["position"] = position
            result = _push_one(client, sdk_attr, o, on_conflict, dry_run, snap_key)
            report.results.append(result)

    # ── Standard objects in dependency order ─────────────────────────────
    for snap_key, sdk_attr, folder in _PUSH_ORDER:
        _process_batch(snap_key, sdk_attr, folder)

    # ── Policy rules ─────────────────────────────────────────────────────
    if not skip_rules:
        for snap_key, sdk_attr, position in _RULE_ORDER:
            _process_batch(snap_key, sdk_attr, "customer", position=position)

    # ── Deployment objects (opt-in) ───────────────────────────────────────
    if include_deployment:
        for snap_key, sdk_attr, folder in _DEPLOY_ORDER:
            _process_batch(
                snap_key,
                sdk_attr,
                folder,
                is_ike_gateway=(sdk_attr == "ike_gateway"),
            )

    return report
